### ISSUE TITLE
Audio drops out

### ISSUE THREAD

**Issue by SethTurin** [s0d3s/PyAudioWPatch#8] opened 2023-03-05 23:24 UTC
When recording system audio, I'm finding the output has large patches of missing audio.  I'm using this library as part of a screen recorder, so it may have something with the load I'm putting on the processor. It's unclear if this is an issue in the library or if there's something I need to do on my end to get it to work better.

Any ideas on what I can do?

**Comment by s0d3s** [comment] 2023-03-09 17:54
Hi🖐

I'm glad to see another your issue, that does not contain useful information. Again.
If you are looking for help, then you must **provide information** that will help me to help you. For example, ~~full~~ some code.

Judging by the information that you nevertheless gave - the architecture of your application blocks execution for a `certain time`. Chunks at this `certain time` are not recorded.

You need to refactor/parallelize the code. Without adequate feedback from you, I can't give a more precise answer.

**Comment by SethTurin** [comment] 2023-03-09 18:26
The script has 3 threads running in parallel. The first thread runs the code from the example in this repository that records system sound. This code is unchanged from the example, except for code that determines when it should stop. the bottom of the function looks like this:

`        with p.open(format=pyaudio.paInt16,
                    channels=default_speakers["maxInputChannels"],
                    rate=int(default_speakers["defaultSampleRate"]),
                    frames_per_buffer=pyaudio.get_sample_size(pyaudio.paInt16),
                    input=True,
                    input_device_index=default_speakers["index"],
                    stream_callback=callback
                    ) as stream:
            """
            Opena PA stream via context manager.
            After leaving the context, everything will
            be correctly closed(Stream, PyAudio manager)            
            """
            while not audio_stopped:
                time.sleep(.01)
        wave_file.close()`

audio_stopped is set to false by default and is set to true when the script receives feedback from the user.

The second thread runs an ffmpeg process to record the screen, and then waits to be closed via a similar mechanism as the first thread.

The third thread collects information about the mouse cursor, which is used later to finish the video.

Is this helpful?

**Comment by s0d3s** [comment] 2023-03-11 20:33
At least so, with this information it is already possible to work. However, not everything is clear. As far as I understand, the piece of code that you showed is executed cyclically (as soon as some event occurs, you interrupt the recording, but after that(and maybe some time) everything starts from the beginning).

In this case, the implementation of audio recording in this form is inappropriate. Opening a new session(`p.open(...)`) consumes too many resources. The time it takes to open a session is not included in the recording.

You must control the recording, __without interrupting__ session. Eg:

```python
#In callback, if condition is True, record audio
def callback(...):
    if not audio_stopped:
        ...
    return (...,)

#Open session at start of thread execution (using callback)
p = pyaudio.PyAudio()
session = p.open(..., stream_callback=callback)

#Some code that blocks execution, until the app closes
...

#Before closing the stream, close the session as well
session.stop_stream()
session.close()
p.terminate()
```

This is a rather abstract example, since the context is still not enough. Perhaps you need to refuse to use a callback, or write audio chunks to a queue and then process them - it all depends on your implementation.

The main thing you have to figure out is how to record audio without closing/opening the recording session.

**Comment by SethTurin** [comment] 2023-03-12 06:21
Thanks for your response. To give more context, what I did was take the code from [this example](https://github.com/s0d3s/PyAudioWPatch/blob/master/examples/pawp_record_wasapi_loopback.py) and stuck it into a function, replacing line 73 with the code that checks the audio_stopped variable. 

At the beginning of the script, the function is run in a new thread. When the recording is complete (which is triggered by the user), audio_stopped is set to true, allowing the function to complete. 

The function is only run once in the script, and once it exits, it does not load again. So unless there's something I'm misunderstanding about the execution flow (which is probable), I don't think the execution is interrupted.

So I don't think anything is interrupting execution, though there is other stuff happening in separate threads.

Is there something I'm still misunderstanding?

**Comment by s0d3s** [comment] 2023-03-13 18:42
If the code is run once, then you should not have problems with sound (in theory). Try to take the code from the example and test it separately from your application (as a separate script), so we will definitely find out if the problem is in the library.

But it is more likely that screen recording and mouse recording take too many resources, and because of this, audio is recorded with problems.

As you wrote above, you use threads to parallelize execution, but there is a convention in python that _all threads share the same resources_. No matter how much you create threads in python, in fact, for the OS (and the corresponding CPU) it will be one thread(If in a nutshell). That is, the processor is not used to its full capacity. In order to achieve not only parallelization of execution, but also an increase in performance, you need to use partitioning not into threads, but into processes.

[More about Threads](https://wiki.python.org/moin/GlobalInterpreterLock)
[multiprocessing](https://docs.python.org/3/library/multiprocessing.html)

**Comment by SethTurin** [comment] 2023-03-13 20:38
Ah, yeah because the OS will delegate to different cores. I'll try this and
report back.

Incidentally, running it in a separate process would also solve the other
issue I was facing.

**Comment by s0d3s** [comment] 2023-03-28 21:01
Any news?

**Closed** 2023-04-12 18:54 UTC
Labels: question, unrelated

**Comment by SethTurin** [comment] 2023-04-16 01:33
Hey

I finally got a chance to give this a try, and I can confirm that running it via multiprocessing did fix the drop out problem, as you expected.

Thanks for your help on this.
